package tn.finhub.util;

import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Phrase;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import tn.finhub.model.User;
import tn.finhub.model.Wallet;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class PdfExporter {

    private static final Font TITLE_FONT = new Font(Font.HELVETICA, 18, Font.BOLD);
    private static final Font SECTION_FONT = new Font(Font.HELVETICA, 14, Font.BOLD);
    private static final Font LABEL_FONT = new Font(Font.HELVETICA, 11, Font.BOLD);
    private static final Font VALUE_FONT = new Font(Font.HELVETICA, 11, Font.NORMAL);
    private static final Font FOOTER_FONT = new Font(Font.HELVETICA, 9, Font.ITALIC);

    public static void exportUserProfile(User user, Wallet wallet, File file) throws IOException, DocumentException {
        if (user == null) {
            throw new IllegalArgumentException("User cannot be null");
        }

        Document document = new Document(PageSize.A4, 40, 40, 40, 40);
        try (FileOutputStream fos = new FileOutputStream(file)) {
            PdfWriter.getInstance(document, fos);
            document.open();

            addTitle(document, user);
            addPersonalInfoSection(document, user);
            addWalletSection(document, wallet);
            addMetaFooter(document);
            document.close();
        }
    }

    private static void addTitle(Document document, User user) throws DocumentException {
        Paragraph title = new Paragraph("FinHub TN - User Profile", TITLE_FONT);
        title.setAlignment(Element.ALIGN_CENTER);
        document.add(title);

        String subtitleText = "Profile summary for " + safe(user.getFullName()) + " (ID: " + user.getId() + ")";
        Paragraph subtitle = new Paragraph(subtitleText, VALUE_FONT);
        subtitle.setAlignment(Element.ALIGN_CENTER);
        subtitle.setSpacingAfter(20f);
        document.add(subtitle);
    }

    private static void addPersonalInfoSection(Document document, User user) throws DocumentException {
        Paragraph section = new Paragraph("Personal Information", SECTION_FONT);
        section.setSpacingBefore(10f);
        section.setSpacingAfter(10f);
        document.add(section);

        PdfPTable table = new PdfPTable(2);
        table.setWidthPercentage(100);
        table.setSpacingAfter(15f);
        table.setWidths(new float[] { 1.5f, 3f });

        addRow(table, "Full Name", safe(user.getFullName()));
        addRow(table, "Email", safe(user.getEmail()));
        addRow(table, "Role", safe(user.getRole()));
        addRow(table, "Trust Score", String.valueOf(user.getTrustScore()));

        document.add(table);
    }

    private static void addWalletSection(Document document, Wallet wallet) throws DocumentException {
        Paragraph section = new Paragraph("Wallet Overview", SECTION_FONT);
        section.setSpacingBefore(5f);
        section.setSpacingAfter(10f);
        document.add(section);

        PdfPTable table = new PdfPTable(2);
        table.setWidthPercentage(100);
        table.setSpacingAfter(15f);
        table.setWidths(new float[] { 1.5f, 3f });

        if (wallet == null) {
            addRow(table, "Status", "No wallet found");
        } else {
            BigDecimal balance = wallet.getBalance() != null ? wallet.getBalance() : BigDecimal.ZERO;
            BigDecimal escrow = wallet.getEscrowBalance() != null ? wallet.getEscrowBalance() : BigDecimal.ZERO;

            addRow(table, "Wallet ID", String.valueOf(wallet.getId()));
            addRow(table, "Currency", safe(wallet.getCurrency()));
            addRow(table, "Main Balance", balance + " " + safe(wallet.getCurrency()));
            addRow(table, "Escrow Balance", escrow + " " + safe(wallet.getCurrency()));
            addRow(table, "Total Funds", balance.add(escrow) + " " + safe(wallet.getCurrency()));
            addRow(table, "Status", safe(wallet.getStatus()));
        }

        document.add(table);
    }

    private static void addMetaFooter(Document document) throws DocumentException {
        document.add(new Paragraph(" "));
        document.add(new Paragraph(" "));

        DateTimeFormatter fmt = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
        String generatedAt = LocalDateTime.now().format(fmt);

        Paragraph footer = new Paragraph(
                "Generated by FinHub TN Admin Console on " + generatedAt,
                FOOTER_FONT);
        footer.setAlignment(Element.ALIGN_RIGHT);
        document.add(footer);
    }

    private static void addRow(PdfPTable table, String label, String value) {
        PdfPCell labelCell = new PdfPCell(new Phrase(label + ":", LABEL_FONT));
        labelCell.setBorderWidth(0);
        labelCell.setPaddingBottom(4f);

        PdfPCell valueCell = new PdfPCell(new Phrase(value, VALUE_FONT));
        valueCell.setBorderWidth(0);
        valueCell.setPaddingBottom(4f);

        table.addCell(labelCell);
        table.addCell(valueCell);
    }

    private static String safe(String s) {
        return s == null || s.isBlank() ? "N/A" : s;
    }
}

